default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: homety_development

test:
  <<: *default
  database: homety_test

production:
  <<: *default
  database: homety_production