default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: linetour_development

test:
  <<: *default
  database: linetour_test

production:
  <<: *default
  database: linetour_production